permalink: /blog/:year/:month/:day/:title

#使用pygments高亮代码
#使自定义的插件无效
#文件发生变动，重新组织工程内容
pygments: true
markdown: rdiscount
safe: true
auto: true

author:
    name : lym
    email : luyueming1989@gmail.com
    github : https://github.com/lym406365619

#设置标签、分类等路径
JB :
    BASE_PATH : false
    categories_path : /categories.html
    tags_path : /tags.html
